#![warn(clippy::all)]
#![cfg_attr(windows, feature(windows_by_handle))]

//! Filesystem walk.
//!
//! - Performed in parallel using rayon
//! - Entries streamed in sorted order
//! - Custom sort/filter/skip/state
//!
//! # Example
//!
//! Recursively iterate over the "foo" directory sorting by name:
//!
//! ```no_run
//! # use std::io::Error;
//! use jwalk_meta::{WalkDir};
//!
//! # fn try_main() -> Result<(), Error> {
//! for entry in WalkDir::new("foo").sort(true) {
//!   println!("{}", entry?.path().display());
//! }
//! # Ok(())
//! # }
//! ```
//! # Extended Example
//!
//! This example uses the
//! [`process_read_dir`](struct.WalkDirGeneric.html#method.process_read_dir)
//! callback for custom:
//! 1. **Sort** Entries by name
//! 2. **Filter** Errors and hidden files
//! 3. **Skip** Content of directories at depth 2
//! 4. **State** Track depth `read_dir_state`. Mark first entry in each
//!    directory with [`client_state`](struct.DirEntry.html#field.client_state)
//!    `= true`.
//!
//! ```no_run
//! # use std::io::Error;
//! use std::cmp::Ordering;
//! use jwalk_meta::{ WalkDirGeneric };
//!
//! # fn try_main() -> Result<(), Error> {
//! let walk_dir = WalkDirGeneric::<((usize),(bool))>::new("foo")
//!     .process_read_dir(|depth, path, read_dir_state, children| {
//!         // 1. Custom sort
//!         children.sort_by(|a, b| match (a, b) {
//!             (Ok(a), Ok(b)) => a.file_name.cmp(&b.file_name),
//!             (Ok(_), Err(_)) => Ordering::Less,
//!             (Err(_), Ok(_)) => Ordering::Greater,
//!             (Err(_), Err(_)) => Ordering::Equal,
//!         });
//!         // 2. Custom filter
//!         children.retain(|dir_entry_result| {
//!             dir_entry_result.as_ref().map(|dir_entry| {
//!                 dir_entry.file_name
//!                     .to_str()
//!                     .map(|s| s.starts_with('.'))
//!                     .unwrap_or(false)
//!             }).unwrap_or(false)
//!         });
//!         // 3. Custom skip
//!         children.iter_mut().for_each(|dir_entry_result| {
//!             if let Ok(dir_entry) = dir_entry_result {
//!                 if dir_entry.depth == 2 {
//!                     dir_entry.read_children_path = None;
//!                 }
//!             }
//!         });
//!         // 4. Custom state
//!         *read_dir_state += 1;
//!         children.first_mut().map(|dir_entry_result| {
//!             if let Ok(dir_entry) = dir_entry_result {
//!                 dir_entry.client_state = true;
//!             }
//!         });
//!     });
//!
//! for entry in walk_dir {
//!   println!("{}", entry?.path().display());
//! }
//! # Ok(())
//! # }
//! ```
//! # Inspiration
//!
//! This crate is inspired by both [`walkdir`](https://crates.io/crates/walkdir)
//! and [`ignore`](https://crates.io/crates/ignore). It attempts to combine the
//! parallelism of `ignore` with `walkdir`'s streaming iterator API. Some code,
//! comments, and test are copied directly from `walkdir`.
//!
//! # Implementation
//!
//! The following structures are central to the implementation:
//!
//! ## `ReadDirSpec`
//!
//! Specification of a future `read_dir` operation. These are stored in the
//! `read_dir_spec_queue` in depth first order. When a rayon thread is ready for
//! work it pulls the first availible `ReadDirSpec` from this queue.
//!
//! ## `ReadDir`
//!
//! Result of a `read_dir` operation generated by rayon thread. These results
//! are stored in the `read_dir_result_queue`, also depth first ordered.
//!
//! ## `ReadDirIter`
//!
//! Pulls `ReadDir` results from the `read_dir_result_queue`. This iterator is
//! driven by calling thread. Results are returned in strict depth first order.
//!
//! ## `DirEntryIter`
//!
//! Wraps a `ReadDirIter` and yields individual `DirEntry` results in strict
//! depth first order.

mod core;

use rayon::ThreadPool;
use std::cmp::Ordering;
use std::ffi::OsStr;
use std::fmt::Debug;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use crate::core::{get_metadata_ext, ReadDir, ReadDirSpec, Weighted};

pub use crate::core::{DirEntry, DirEntryIter, Error, MetaData, MetaDataExt};
pub use rayon;

/// Builder for walking a directory.
pub type WalkDir = WalkDirGeneric<((), ())>;

/// A specialized Result type for WalkDir.
pub type Result<T> = std::result::Result<T, Error>;

/// Client state maintained while performing walk.
///
/// for state stored in DirEntry's
/// [`client_state`](struct.DirEntry.html#field.client_state) field.
///
/// Client state can be stored from within the
/// [`process_read_dir`](struct.WalkDirGeneric.html#method.process_read_dir) callback.
/// The type of ClientState is determined by WalkDirGeneric type parameter.
pub trait ClientState: Send + Default + Debug + 'static {
    type ReadDirState: Clone + Send + Default + Debug + 'static;
    type DirEntryState: Send + Default + Debug + 'static;
}

/// Generic builder for walking a directory.
///
/// [`ClientState`](trait.ClientState.html) type parameter allows you to specify
/// state to be stored with each DirEntry from within the
/// [`process_read_dir`](struct.WalkDirGeneric.html#method.process_read_dir)
/// callback.
///
/// Use [`WalkDir`](type.WalkDir.html) if you don't need to store client state
/// into yeilded DirEntries.
pub struct WalkDirGeneric<C: ClientState> {
    root: PathBuf,
    options: WalkDirOptions<C>,
}

type ProcessReadDirFunction<C> = dyn Fn(Option<usize>, &Path, &mut <C as ClientState>::ReadDirState, &mut Vec<Result<DirEntry<C>>>)
    + Send
    + Sync
    + 'static;

/// Degree of parallelism to use when performing walk.
///
/// Parallelism happens at the directory level. It will help when walking deep
/// filesystems with many directories. It wont help when reading a single
/// directory with many files.
///
/// If you plan to perform lots of per file processing you might want to use Rayon to
#[derive(Clone)]
pub enum Parallelism {
    /// Run on calling thread, similar to what happens in the `walkdir` crate.
    Serial,
    /// Run in default rayon thread pool.
    RayonDefaultPool {
        /// Define when we consider the rayon default pool too busy to serve our iteration and abort the iteration, defaulting to 1s.
        ///
        /// This can happen if `jwalk_meta` is launched from within a par-iter on a pool that only has a single thread,
        /// or if there are many parallel `jwalk_meta` invocations that all use the same threadpool, rendering it too busy
        /// to respond within this duration.
        busy_timeout: std::time::Duration,
    },
    /// Run in existing rayon thread pool
    RayonExistingPool {
        /// The pool to spawn our work onto.
        pool: Arc<ThreadPool>,
        /// Similar to [`Parallelism::RayonDefaultPool::busy_timeout`] if `Some`, but can be `None` to skip the deadlock check
        /// in case you know that there is at least one free thread available on the pool.
        busy_timeout: Option<std::time::Duration>,
    },
    /// Run in new rayon thread pool with # threads
    RayonNewPool(usize),
}

struct WalkDirOptions<C: ClientState> {
    sort: bool,
    min_depth: usize,
    max_depth: usize,
    skip_hidden: bool,
    follow_links: bool,
    read_metadata: bool,
    read_metadata_ext: bool,
    /// NT 枚举结果 Vec 的预分配容量（仅 Windows 生效）。
    /// 大目录场景可调高减少重分配，小目录场景可调低节省内存。默认 512。
    dir_entry_capacity: usize,
    parallelism: Parallelism,
    root_read_dir_state: C::ReadDirState,
    process_read_dir: Option<Arc<ProcessReadDirFunction<C>>>,
}

impl<C: ClientState> WalkDirGeneric<C> {
    /// Create a builder for a recursive directory iterator starting at the file
    /// path root. If root is a directory, then it is the first item yielded by
    /// the iterator. If root is a file, then it is the first and only item
    /// yielded by the iterator.
    ///
    /// Note that his iterator can fail on the first element if `into_iter()` is used as it
    /// has to be infallible. Use [`try_into_iter()`][WalkDirGeneric::try_into_iter()]
    /// instead for error handling.
    pub fn new<P: AsRef<Path>>(root: P) -> Self {
        WalkDirGeneric {
            root: root.as_ref().to_path_buf(),
            options: WalkDirOptions {
            sort: false,
                min_depth: 0,
                max_depth: usize::MAX,
                skip_hidden: false,
                follow_links: false,
                read_metadata: false,
                read_metadata_ext: false,
                dir_entry_capacity: 512,
                parallelism: Parallelism::RayonDefaultPool {
                    busy_timeout: std::time::Duration::from_secs(1),
                },
                root_read_dir_state: C::ReadDirState::default(),
                process_read_dir: None,
            },
        }
    }

    /// Try to create an iterator or fail if the rayon threadpool (in any configuration) is busy.
    pub fn try_into_iter(self) -> Result<DirEntryIter<C>> {
        let iter = self.into_iter();
        if iter.read_dir_iter.is_none() {
            Err(Error::busy())
        } else {
            Ok(iter)
        }
    }

    /// Root path of the walk.
    pub fn root(&self) -> &Path {
        &self.root
    }

    /// Sort entries by `file_name` per directory. Defaults to `false`. Use
    /// [`process_read_dir`](struct.WalkDirGeneric.html#method.process_read_dir) for custom
    /// sorting or filtering.
    pub fn sort(mut self, sort: bool) -> Self {
        self.options.sort = sort;
        self
    }

    /// Skip hidden entries. Disabled by default.
    pub fn skip_hidden(mut self, skip_hidden: bool) -> Self {
        self.options.skip_hidden = skip_hidden;
        self
    }

    /// Follow symbolic links. By default, this is disabled.
    ///
    /// When `yes` is `true`, symbolic links are followed as if they were normal
    /// directories and files. If a symbolic link is broken or is involved in a
    /// loop, an error is yielded.
    ///
    /// When enabled, the yielded [`DirEntry`] values represent the target of
    /// the link while the path corresponds to the link. See the [`DirEntry`]
    /// type for more details.
    ///
    /// [`DirEntry`]: struct.DirEntry.html
    pub fn follow_links(mut self, follow_links: bool) -> Self {
        self.options.follow_links = follow_links;
        self
    }

    /// Set the minimum depth of entries yielded by the iterator.
    ///
    /// The smallest depth is `0` and always corresponds to the path given
    /// to the `new` function on this type. Its direct descendents have depth
    /// `1`, and their descendents have depth `2`, and so on.
    pub fn min_depth(mut self, depth: usize) -> Self {
        self.options.min_depth = depth;
        if self.options.min_depth > self.options.max_depth {
            self.options.min_depth = self.options.max_depth;
        }
        self
    }

    /// Set the maximum depth of entries yield by the iterator.
    ///
    /// The smallest depth is `0` and always corresponds to the path given
    /// to the `new` function on this type. Its direct descendents have depth
    /// `1`, and their descendents have depth `2`, and so on.
    ///
    /// A depth < 2 will automatically change `parallelism` to
    /// `Parallelism::Serial`. Parrallelism happens at the `fs::read_dir` level.
    /// It only makes sense to use multiple threads when reading more then one
    /// directory.
    ///
    /// Note that this will not simply filter the entries of the iterator, but
    /// it will actually avoid descending into directories when the depth is
    /// exceeded.
    pub fn max_depth(mut self, depth: usize) -> Self {
        self.options.max_depth = depth;
        if self.options.max_depth < self.options.min_depth {
            self.options.max_depth = self.options.min_depth;
        }
        if self.options.max_depth < 2 {
            self.options.parallelism = Parallelism::Serial;
        }
        self
    }

    /// Read OS independent metadata
    pub fn read_metadata(mut self, read_metadata: bool) -> Self {
        self.options.read_metadata = read_metadata;
        self
    }

    /// Read Os dependent metadata
    pub fn read_metadata_ext(mut self, read_metadata_ext: bool) -> Self {
        self.options.read_metadata_ext = read_metadata_ext;
        self
    }

    /// Set the pre-allocated capacity for the directory entry result vector.
    ///
    /// This controls the initial `Vec::with_capacity()` used when enumerating
    /// directory entries via the NT Native API (Windows only). For directories
    /// with many files (e.g. 10000+), increasing this value reduces Vec
    /// re-allocations. For small directories, decreasing it saves memory.
    /// Defaults to `512`.
    pub fn dir_entry_capacity(mut self, capacity: usize) -> Self {
        self.options.dir_entry_capacity = capacity;
        self
    }

    /// Degree of parallelism to use when performing walk. Defaults to
    /// [`Parallelism::RayonDefaultPool`](enum.Parallelism.html#variant.RayonDefaultPool).
    pub fn parallelism(mut self, parallelism: Parallelism) -> Self {
        self.options.parallelism = parallelism;
        self
    }

    /// Initial ClientState::ReadDirState that is passed to
    /// [`process_read_dir`](struct.WalkDirGeneric.html#method.process_read_dir)
    /// when processing root. Defaults to ClientState::ReadDirState::default().
    pub fn root_read_dir_state(mut self, read_dir_state: C::ReadDirState) -> Self {
        self.options.root_read_dir_state = read_dir_state;
        self
    }

    /// A callback function to process (sort/filter/skip/state) each directory
    /// of entries before they are yielded. Modify the given array to
    /// sort/filter entries. Use [`entry.read_children_path =
    /// None`](struct.DirEntry.html#field.read_children_path) to yield a
    /// directory entry but skip reading its contents. Use
    /// [`entry.client_state`](struct.DirEntry.html#field.client_state)
    /// to store custom state with an entry.
    pub fn process_read_dir<F>(mut self, process_by: F) -> Self
    where
        F: Fn(Option<usize>, &Path, &mut C::ReadDirState, &mut Vec<Result<DirEntry<C>>>)
            + Send
            + Sync
            + 'static,
    {
        self.options.process_read_dir = Some(Arc::new(process_by));
        self
    }
}

fn process_dir_entry_result<C: ClientState>(
    dir_entry_result: Result<DirEntry<C>>,
    follow_links: bool,
) -> Result<DirEntry<C>> {
    match dir_entry_result {
        Ok(mut dir_entry) => {
            if follow_links && dir_entry.file_type.is_symlink() {
                dir_entry = dir_entry.follow_symlink()?;
            }

            if dir_entry.depth == 0 && dir_entry.file_type.is_symlink() {
                // As a special case, if we are processing a root entry, then we
                // always follow it even if it's a symlink and follow_links is
                // false. We are careful to not let this change the semantics of
                // the DirEntry however. Namely, the DirEntry should still
                // respect the follow_links setting. When it's disabled, it
                // should report itself as a symlink. When it's enabled, it
                // should always report itself as the target.
                let metadata = fs::metadata(dir_entry.path())
                    .map_err(|err| Error::from_path(0, dir_entry.path().to_owned(), err))?;
                if metadata.file_type().is_dir() {
                    dir_entry.read_children_path = Some(Arc::from(dir_entry.path()));
                }
            }

            Ok(dir_entry)
        }
        Err(err) => Err(err),
    }
}

impl<C: ClientState> IntoIterator for WalkDirGeneric<C> {
    type Item = Result<DirEntry<C>>;
    type IntoIter = DirEntryIter<C>;

    fn into_iter(self) -> DirEntryIter<C> {
        let sort = self.options.sort;
        let max_depth = self.options.max_depth;
        let min_depth = self.options.min_depth;
        let parallelism = self.options.parallelism;
        let skip_hidden = self.options.skip_hidden;
        let follow_links = self.options.follow_links;
        let read_metadata = self.options.read_metadata;
        let read_metadata_ext = self.options.read_metadata_ext;
        let dir_entry_capacity = self.options.dir_entry_capacity;
        let process_read_dir = self.options.process_read_dir.clone();
        let mut root_read_dir_state = self.options.root_read_dir_state;
        let follow_link_ancestors: Option<Arc<Vec<Arc<Path>>>> = if follow_links {
            Some(Arc::new(vec![Arc::from(self.root.clone()) as Arc<Path>]))
        } else {
            None
        };

        let root_entry = DirEntry::from_path(
            0,
            &self.root,
            read_metadata,
            read_metadata_ext,
            false,
            follow_link_ancestors,
        );
        let root_parent_path = root_entry
            .as_ref()
            .map(|root| root.parent_path().to_owned())
            .unwrap_or_default();
        let mut root_entry_results = vec![process_dir_entry_result(root_entry, follow_links)];
        if let Some(process_read_dir) = process_read_dir.as_ref() {
            process_read_dir(
                None,
                &root_parent_path,
                &mut root_read_dir_state,
                &mut root_entry_results,
            );
        }

        DirEntryIter::new(
            root_entry_results,
            parallelism,
            min_depth,
            root_read_dir_state,
            Arc::new(move |read_dir_spec, streaming_ctx| {
                let ReadDirSpec {
                    path,
                    depth,
                    client_read_state,
                    mut follow_link_ancestors,
                } = read_dir_spec;

                let read_dir_depth = depth;
                // saturating_add 防止 depth=usize::MAX 时溢出
                let read_dir_contents_depth = depth.saturating_add(1);

                if read_dir_contents_depth > max_depth {
                    return Ok(ReadDir::new(client_read_state, Vec::new()));
                }

                follow_link_ancestors = if follow_links {
                    let existing = follow_link_ancestors
                        .as_ref()
                        .map(|a| a.as_ref().as_slice())
                        .unwrap_or(&[]);
                    let mut ancestors = Vec::with_capacity(existing.len() + 1);
                    ancestors.extend(existing.iter().cloned());
                    ancestors.push(path.clone());
                    Some(Arc::new(ancestors))
                } else {
                    follow_link_ancestors
                };

                #[cfg(windows)]
                {
                    read_dir_windows(
                        path,
                        read_dir_depth,
                        read_dir_contents_depth,
                        follow_links,
                        read_metadata,
                        read_metadata_ext,
                        dir_entry_capacity,
                        skip_hidden,
                        sort,
                        follow_link_ancestors,
                        client_read_state,
                        process_read_dir.as_ref(),
                        streaming_ctx,
                    )
                }

                #[cfg(not(windows))]
                {
                    let _ = streaming_ctx; // 消除 unused 警告
                    read_dir_unix(
                        path,
                        read_dir_depth,
                        read_dir_contents_depth,
                        follow_links,
                        read_metadata,
                        read_metadata_ext,
                        skip_hidden,
                        sort,
                        follow_link_ancestors,
                        client_read_state,
                        process_read_dir.as_ref(),
                    )
                }
            }),
        )
    }
}

impl<C: ClientState> Clone for WalkDirOptions<C> {
    fn clone(&self) -> WalkDirOptions<C> {
        WalkDirOptions {
            sort: self.sort,
            min_depth: self.min_depth,
            max_depth: self.max_depth,
            skip_hidden: self.skip_hidden,
            follow_links: self.follow_links,
            read_metadata: self.read_metadata,
            read_metadata_ext: self.read_metadata_ext,
            dir_entry_capacity: self.dir_entry_capacity,
            parallelism: self.parallelism.clone(),
            root_read_dir_state: self.root_read_dir_state.clone(),
            process_read_dir: self.process_read_dir.clone(),
        }
    }
}

impl Parallelism {
    pub(crate) fn spawn<OP>(&self, op: OP)
    where
        OP: FnOnce() + Send + 'static,
    {
        match self {
            Parallelism::Serial => op(),
            Parallelism::RayonDefaultPool { .. } => rayon::spawn(op),
            Parallelism::RayonNewPool(num_threads) => {
                // TLS 线程池复用（jwalk-meta-naz / jwalk-meta-8cl）：
                // 同一线程内所有 WalkDir 实例共享同一个 ThreadPool，
                // 避免频繁创建/销毁线程池的开销。
                // 线程池随宿主线程生命周期销毁，rayon::ThreadPool::drop 会
                // 等待所有工作线程完成后才释放资源。
                thread_local! {
                    static TLS_POOL: std::cell::RefCell<Option<rayon::ThreadPool>> = std::cell::RefCell::new(None);
                }
                TLS_POOL.with(|cell| {
                    let mut pool_opt = cell.borrow_mut();
                    if pool_opt.is_none() {
                        let mut builder = rayon::ThreadPoolBuilder::new();
                        if *num_threads > 0 {
                            builder = builder.num_threads(*num_threads);
                        }
                        *pool_opt = builder.build().ok();
                    }
                    if let Some(pool) = pool_opt.as_ref() {
                        pool.spawn(op);
                    } else {
                        rayon::spawn(op);
                    }
                })
            }
            Parallelism::RayonExistingPool { pool, .. } => pool.spawn(op),
        }
    }

    pub(crate) fn timeout(&self) -> Option<std::time::Duration> {
        match self {
            Parallelism::Serial | Parallelism::RayonNewPool(_) => None,
            Parallelism::RayonDefaultPool { busy_timeout } => Some(*busy_timeout),
            Parallelism::RayonExistingPool { busy_timeout, .. } => *busy_timeout,
        }
    }
}

#[cfg(not(windows))]
fn is_hidden(file_name: &OsStr) -> bool {
    file_name.as_bytes().first() == Some(b'.')
}

#[cfg(windows)]
fn is_hidden(file_name: &OsStr) -> bool {
    file_name.as_encoded_bytes().first() == Some(&b'.')
}

/// Windows 文件属性常量
#[cfg(windows)]
mod win32_attrs {
    /// 目录属性位
    pub const FILE_ATTRIBUTE_DIRECTORY: u32 = 0x10;
    /// 符号链接/重解析点属性位
    pub const FILE_ATTRIBUTE_REPARSE_POINT: u32 = 0x400;
    /// 隐藏文件属性位
    pub const FILE_ATTRIBUTE_HIDDEN: u32 = 0x2;
}

/// Windows 扩展版 is_hidden：同时检查 dot 前缀和 FILE_ATTRIBUTE_HIDDEN 属性位。
#[cfg(windows)]
fn is_hidden_win32(file_name: &OsStr, file_attributes: u32) -> bool {
    if file_attributes & win32_attrs::FILE_ATTRIBUTE_HIDDEN != 0 {
        return true;
    }
    is_hidden(file_name)
}

// ── Windows NT fast-path 辅助函数 ─────────────────────────────────────

#[cfg(windows)]
mod read_dir_windows_helpers {
    use super::*;
    use crate::core::DirEntryInfo;

    // Windows FILETIME epoch (1601-01-01) to UNIX epoch offset in 100ns ticks
    pub(super) const EPOCH_DIFFERENCE_100NS: i64 = 116_444_736_000_000_000;
    /// 100-ns ticks per second (FILETIME precision)
    pub(super) const HUNDRED_NS_PER_SEC: i64 = 10_000_000;
    /// Nanoseconds per 100-ns tick
    pub(super) const NS_PER_HUNDRED_NS: i64 = 100;

    /// 将 Windows FILETIME (100-ns ticks since 1601) 转为 SystemTime
    pub(super) fn filetime_to_systemtime(ft: i64) -> Option<std::time::SystemTime> {
        if ft == 0 { return None; }
        let duration_100ns = ft.saturating_sub(EPOCH_DIFFERENCE_100NS);
        if duration_100ns < 0 { return None; }
        let secs = (duration_100ns / HUNDRED_NS_PER_SEC) as u64;
        let nanos = ((duration_100ns % HUNDRED_NS_PER_SEC) * NS_PER_HUNDRED_NS) as u32;
        Some(std::time::UNIX_EPOCH + std::time::Duration::new(secs, nanos))
    }

    /// 从 file_attributes (u32) 构造 std::fs::FileType
    ///
    /// SAFETY: 此 transmute 依赖 std::fs::FileType 的内部布局。
    /// 在 Windows 上 FileType 内部存储为 `[bool; 2]`（is_dir, is_symlink），
    /// 实际以 `u16` 表示：byte 0 = is_dir, byte 1 = is_symlink。
    ///
    /// 注意：std 并未保证此布局稳定。如果 Rust 标准库未来更改 FileType
    /// 的内部表示，此 transmute 将产生未定义行为。更安全的替代方案是
    /// 使用 `From<u32>` 或 `FromRawOs` 等 API（当稳定后）。
    ///
    /// 依赖的布局定义位于（Rust 1.x）：
    /// `library/std/src/sys/pal/windows/fs.rs: FileType { is_directory: bool, is_symlink: bool }`
    pub(super) fn file_type_from_attrs(attrs: u32) -> std::fs::FileType {
        // 运行时校验：确保 u16 与 FileType 大小一致，
        // 防止 std 更改布局后静默 UB
        const _: () = assert!(
            std::mem::size_of::<std::fs::FileType>() == std::mem::size_of::<u16>(),
            "FileType layout assumption violated: expected 2 bytes"
        );
        let is_dir = (attrs & win32_attrs::FILE_ATTRIBUTE_DIRECTORY) != 0;
        let is_sym = (attrs & win32_attrs::FILE_ATTRIBUTE_REPARSE_POINT) != 0;
        let bits: u16 = (is_dir as u16) | ((is_sym as u16) << 8);
        unsafe { std::mem::transmute(bits) }
    }

    /// 从 DirEntryInfo 构造 MetaData
    pub(super) fn make_metadata(info: &DirEntryInfo) -> MetaData {
        let ft = file_type_from_attrs(info.file_attributes);
        MetaData {
            is_dir: ft.is_dir(),
            is_file: ft.is_file(),
            is_symlink: ft.is_symlink(),
            size: info.file_size,
            created: filetime_to_systemtime(info.creation_time),
            modified: filetime_to_systemtime(info.last_write_time),
            accessed: filetime_to_systemtime(info.last_access_time),
            permissions: None, // NT fast path 不获取权限信息
        }
    }

    /// 从 DirEntryInfo 构造 MetaDataExt
    pub(super) fn make_metadata_ext(info: &DirEntryInfo) -> MetaDataExt {
        MetaDataExt {
            file_attributes: info.file_attributes,
            volume_serial_number: None,
            number_of_links: None,
            file_index: Some(info.file_id),
        }
    }

    /// 从 DirEntryInfo 构造 DirEntry
    pub(super) fn make_dir_entry<C: ClientState>(
        info: &DirEntryInfo,
        depth: usize,
        parent_path: Arc<Path>,
        read_metadata: bool,
        read_metadata_ext: bool,
        follow_link_ancestors: Option<Arc<Vec<Arc<Path>>>>,
    ) -> Result<DirEntry<C>> {
        let entry_metadata = if read_metadata {
            Some(make_metadata(info))
        } else {
            None
        };
        let entry_metadata_ext = if read_metadata_ext {
            Some(make_metadata_ext(info))
        } else {
            None
        };
        let file_type = file_type_from_attrs(info.file_attributes);
        DirEntry::from_raw(
            depth,
            parent_path,
            entry_metadata,
            entry_metadata_ext,
            info.file_name.clone(),
            file_type,
            follow_link_ancestors,
        )
    }
}

impl<B, E> ClientState for (B, E)
where
    B: Clone + Send + Default + Debug + 'static,
    E: Send + Default + Debug + 'static,
{
    type ReadDirState = B;
    type DirEntryState = E;
}

// ── 平台特定的 read_dir 实现 ─────────────────────────────────────────

/// Windows NT Native API fast path：使用 NtQueryDirectoryFileEx 枚举目录。
///
/// 支持流式子目录分发（streaming）和常规批量枚举两种模式。
#[cfg(windows)]
fn read_dir_windows<C: ClientState>(
    path: Arc<Path>,
    read_dir_depth: usize,
    read_dir_contents_depth: usize,
    follow_links: bool,
    read_metadata: bool,
    read_metadata_ext: bool,
    dir_entry_capacity: usize,
    skip_hidden: bool,
    sort: bool,
    follow_link_ancestors: Option<Arc<Vec<Arc<Path>>>>,
    mut client_read_state: C::ReadDirState,
    process_read_dir: Option<&Arc<ProcessReadDirFunction<C>>>,
    streaming_ctx: Option<crate::core::StreamingContext<C>>,
) -> Result<ReadDir<C>> {
    use crate::core::{enumerate_dir, enumerate_dir_streaming};
    use read_dir_windows_helpers::*;

    // 选择枚举策略：流式 vs 非流式
    let use_streaming = streaming_ctx.is_some() && !sort && process_read_dir.is_none();

    // Cell<usize> 允许闭包内修改，不受 Copy 语义影响
    let streamed_count = std::cell::Cell::new(0usize);

    let entries_result = if use_streaming {
        // ── 流式分发路径 ──
        // 准备 IndexPath：克隆基路径并 push(0)，回调中递增最后一个元素
        let mut child_index_path = streaming_ctx.as_ref().unwrap().index_path.clone();
        child_index_path.indices.push(0);

        let ctx = streaming_ctx.as_ref().unwrap();

        // 优先淹没算法：weight = parent_weight + subdir_count
        // parent_weight 继承父目录权重（大管道的分支也是大管道）
        // subdir_count 递增确保子目录越多的父目录权重越高
        let parent_weight = ctx.parent_weight;

        enumerate_dir_streaming(path.as_ref(), dir_entry_capacity, |dir_info| {
            // 检查停止标志 — 如果遍历被取消则立即退出
            if ctx.is_stopped() {
                return;
            }

            // 跳过隐藏目录
            if skip_hidden && is_hidden_win32(&dir_info.file_name, dir_info.file_attributes) {
                return;
            }

            // 检查是否为目录
            if dir_info.file_attributes & win32_attrs::FILE_ATTRIBUTE_DIRECTORY == 0 {
                return; // 只分发子目录
            }

            let child_path: Arc<Path> = Arc::from(
                path.join(&dir_info.file_name)
            );
            let spec = ReadDirSpec {
                depth: read_dir_contents_depth,
                path: child_path,
                client_read_state: client_read_state.clone(),
                follow_link_ancestors: follow_link_ancestors.clone(),
            };

        // 优先淹没算法：统一权重策略
        // 流式路径：weight = parent_weight + (streamed_count + 1)
        // 非流式路径(read_dir.rs)：weight = parent_weight + pipe_size
        //
        // 流式阶段 pipe_size 尚不可知（枚举未完成），
        // 使用 streamed_count+1 作为递增权重下界，
        // 确保先发现的子目录先被调度（BFS倾向）。
        // 枚举完成后非流式部分使用完整 pipe_size 统一权重。
        let weight = parent_weight.saturating_add(streamed_count.get() + 1);
            if let Some(last) = child_index_path.indices.last_mut() {
                *last = streamed_count.get();
            }
            if ctx.schedule(Weighted::new(spec, child_index_path.clone(), weight)) {
                streamed_count.set(streamed_count.get() + 1);
            }
        })
    } else {
        // ── 非流式路径 ──
        enumerate_dir(path.as_ref(), dir_entry_capacity)
    };

    let streamed_child_count = streamed_count.get();

    let entries = match entries_result {
        Ok(e) => e,
        Err(err) => {
            // 如果流式枚举在出错前已调度了子目录，必须报告已调度数量，
            // 否则 OrderedQueue 的 pending_count 会不匹配，导致消费者永远挂起。
            // 返回包含错误 DirEntry 的 ReadDir，携带正确的 streamed_child_count。
            if streamed_child_count > 0 {
                let mut read_dir = ReadDir::new(client_read_state, vec![Err(Error::from_path(0, path.to_path_buf(), err))]);
                read_dir.streamed_child_count = streamed_child_count;
                return Ok(read_dir);
            }
            return Err(Error::from_path(0, path.to_path_buf(), err));
        }
    };

    // 构造 DirEntry 列表
    let mut dir_entry_results: Vec<_> = entries
        .iter()
        .filter_map(|info| {
            if skip_hidden && is_hidden_win32(&info.file_name, info.file_attributes) {
                return None;
            }

            let dir_entry = match make_dir_entry(
                info,
                read_dir_contents_depth,
                path.clone(),
                read_metadata,
                read_metadata_ext,
                follow_link_ancestors.clone(),
            ) {
                Ok(e) => e,
                Err(err) => return Some(Err(err)),
            };

            Some(process_dir_entry_result(Ok(dir_entry), follow_links))
        })
        .collect();

    if sort {
        dir_entry_results.sort_unstable_by(|a, b| match (a, b) {
            (Ok(a), Ok(b)) => a.file_name.cmp(&b.file_name),
            (Ok(_), Err(_)) => Ordering::Less,
            (Err(_), Ok(_)) => Ordering::Greater,
            (Err(_), Err(_)) => Ordering::Equal,
        });
    }

    if let Some(process_read_dir) = process_read_dir {
        process_read_dir(
            Some(read_dir_depth),
            path.as_ref(),
            &mut client_read_state,
            &mut dir_entry_results,
        );
    }

    let mut read_dir = ReadDir::new(client_read_state, dir_entry_results);
    read_dir.streamed_child_count = streamed_child_count;
    Ok(read_dir)
}

/// 非 Windows 路径：使用 fs::read_dir 枚举目录。
#[cfg(not(windows))]
fn read_dir_unix<C: ClientState>(
    path: Arc<Path>,
    read_dir_depth: usize,
    read_dir_contents_depth: usize,
    follow_links: bool,
    read_metadata: bool,
    read_metadata_ext: bool,
    skip_hidden: bool,
    sort: bool,
    follow_link_ancestors: Option<Arc<Vec<Arc<Path>>>>,
    mut client_read_state: C::ReadDirState,
    process_read_dir: Option<&Arc<ProcessReadDirFunction<C>>>,
) -> Result<ReadDir<C>> {
    let mut dir_entry_results: Vec<_> = fs::read_dir(path.as_ref())
        .map_err(|err| Error::from_path(0, path.to_path_buf(), err))?
        .filter_map(|dir_entry_result| {
            let fs_dir_entry = match dir_entry_result {
                Ok(fs_dir_entry) => fs_dir_entry,
                Err(err) => {
                    return Some(Err(Error::from_io(read_dir_contents_depth, err)))
                }
            };

            let mut entry_metadata = None;
            let mut entry_metadata_ext = None;
            if read_metadata {
                if let Ok(metadata) = fs_dir_entry.metadata() {
                    if read_metadata_ext {
                        entry_metadata_ext = Some(get_metadata_ext(&metadata));
                    }
                    entry_metadata = Some(MetaData {
                        is_dir: metadata.is_dir(),
                        is_file: metadata.is_file(),
                        is_symlink: metadata.is_symlink(),
                        size: metadata.len(),
                        created: metadata.created().ok(),
                        modified: metadata.modified().ok(),
                        accessed: metadata.accessed().ok(),
                        permissions: Some(metadata.permissions()),
                    });
                } else if let Ok(file_type) = fs_dir_entry.file_type() {
                    entry_metadata = Some(MetaData {
                        is_dir: file_type.is_dir(),
                        is_file: file_type.is_file(),
                        is_symlink: file_type.is_symlink(),
                        size: 0,
                        created: None,
                        modified: None,
                        accessed: None,
                        permissions: None,
                    });
                }
            } else if read_metadata_ext {
                if let Ok(metadata) = fs::metadata(fs_dir_entry.path()) {
                    entry_metadata_ext = Some(get_metadata_ext(&metadata));
                }
            }

            let dir_entry = match DirEntry::from_entry(
                read_dir_contents_depth,
                path.clone(),
                entry_metadata,
                entry_metadata_ext,
                &fs_dir_entry,
                follow_link_ancestors.clone(),
            ) {
                Ok(dir_entry) => dir_entry,
                Err(err) => return Some(Err(err)),
            };

            if skip_hidden && is_hidden(&dir_entry.file_name) {
                return None;
            }

            Some(process_dir_entry_result(Ok(dir_entry), follow_links))
        })
        .collect();

    if sort {
        dir_entry_results.sort_unstable_by(|a, b| match (a, b) {
            (Ok(a), Ok(b)) => a.file_name.cmp(&b.file_name),
            (Ok(_), Err(_)) => Ordering::Less,
            (Err(_), Ok(_)) => Ordering::Greater,
            (Err(_), Err(_)) => Ordering::Equal,
        });
    }

    if let Some(process_read_dir) = process_read_dir {
        process_read_dir(
            Some(read_dir_depth),
            path.as_ref(),
            &mut client_read_state,
            &mut dir_entry_results,
        );
    }

    Ok(ReadDir::new(client_read_state, dir_entry_results))
}
